/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `hq-payments` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `hq-payments`;

CREATE TABLE IF NOT EXISTS `payment` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRICE` int(15) NOT NULL,
  `CURRENCY` varchar(10) NOT NULL,
  `CUSTOMER_NAME` varchar(200) NOT NULL,
  `CREDIT_CARD_HOLDER_NAME` varchar(200) NOT NULL,
  `CREDIT_CARD_TYPE` varchar(100) NOT NULL,
  `CREDIT_CARD_NUMBER` varchar(100) NOT NULL,
  `CREDIT_CARD_EXPIRATION` varchar(100) NOT NULL,
  `CCV` int(6) NOT NULL,
  `PROVIDER_RESULT` TEXT NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8;



